-- Run this in Supabase SQL editor

create table if not exists public.lumea_users (
    id bigint generated by default as identity primary key,
    email text not null unique,
    password_hash text not null,
    first_name text not null,
    last_name text not null,
    phone text,
    street text,
    city text,
    postal_code text,
    account_type text not null default 'customer',
    created_at timestamptz not null default now()
);

create table if not exists public.lumea_products (
    id bigint primary key,
    name text not null,
    category text not null,
    price numeric(10,2) not null default 0,
    rating numeric(3,2) not null default 0,
    rating_count integer not null default 0,
    featured boolean not null default false,
    image_url text,
    images jsonb not null default '[]'::jsonb,
    description text,
    details jsonb not null default '[]'::jsonb,
    options jsonb not null default '[]'::jsonb,
    reviews jsonb not null default '[]'::jsonb,
    stock integer not null default 0,
    status text not null default 'In Stock',
    updated_at timestamptz not null default now()
);

create table if not exists public.lumea_cart_items (
    id bigint generated by default as identity primary key,
    user_email text not null,
    product_id text not null,
    qty integer not null check (qty > 0),
    updated_at timestamptz not null default now(),
    unique (user_email, product_id)
);

create index if not exists idx_lumea_cart_items_user_email on public.lumea_cart_items (user_email);

alter table public.lumea_users enable row level security;
alter table public.lumea_products enable row level security;
alter table public.lumea_cart_items enable row level security;

-- Temporary permissive policies for deadline/demo deployment.
-- Tighten these policies before production use.
drop policy if exists "public users access" on public.lumea_users;
create policy "public users access" on public.lumea_users for all using (true) with check (true);

drop policy if exists "public products access" on public.lumea_products;
create policy "public products access" on public.lumea_products for all using (true) with check (true);

drop policy if exists "public cart access" on public.lumea_cart_items;
create policy "public cart access" on public.lumea_cart_items for all using (true) with check (true);
